env: "local" # Окружение - local, dev или prod
storage:
  path: "./storage/storage.db" # файл, в котором будет храниться наша БД
http_server: # конфигурация нашего http-сервера
  address: ":8082"
  timeout: 4s
  idle_timeout: 30s
  password: hla
  user: hla